[package]
authors = ["Yohai Berreby (yberreby) <yohaiberreby@gmail.com>"]
name = "rulis-parser"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
lalrpop = "0.12.0"

[dependencies]
lalrpop-util = "0.12.0"
